FROM ubuntu:18.04

MAINTAINER Rafael Cabañas <rcabanas@ual.es>


RUN apt-get update 

# Install pip
RUN apt-get install -y python3-pip

# Set current working directory
WORKDIR /home/root/

RUN pip3 install --upgrade pip


# Install Inferpy

RUN pip3 install inferpy






    





